### ISSUE TITLE
VS 2013 Express wont load FidoU2F project

### ISSUE THREAD

**Issue by BillBartlett503** [hanswolff/fido-u2f-net#1]
I downloaded and expanded the zip file.  When I open the solution in VS2013 the project FidoU2F is reported as incompatible with the current version of VS.

**Comment by shana** [comment]
@BillBartlett503 FYI, as a workdaround, just open the csproj file in a text editor and change the value of `ToolsVersion` from `14.0` to `12.0`.

**Comment by hanswolff** [comment]
thanks for figuring that out, I've fixed the project files in 927b1ccd07d186bb0b5cfd80a0da25d68bc2dcde
